<?php
/**
 * Single source of product data. Require once per request; sets $products.
 * Used by products.php, product.php, cart.php, checkout.php, success.php.
 */
require_once __DIR__ . '/config.php';

$products = [
        [
            'id' => 1,
            'name' => 'Indestructible Chew Toy',
            'slug' => 'indestructible-chew-toy',
            'category' => 'Play & Teething',
            'price' => 8200,
            'price_usd' => 5.47,
            'shortDescription' => 'Durable, non-toxic chew toy for teething puppies',
            'description' => 'Made from 100% food-grade rubber, this indestructible chew toy is perfect for teething puppies. Designed to soothe sore gums while redirecting destructive chewing away from furniture. Non-toxic and dishwasher safe for easy cleaning.',
            'images' => [
                '/products/indestructible-chew-toy/indestructible-chew-toy-1.jpg',
                '/products/indestructible-chew-toy/indestructible-chew-toy-2.jpg',
                '/products/indestructible-chew-toy/indestructible-chew-toy-3.jpg',
                '/products/indestructible-chew-toy/indestructible-chew-toy-4.jpg',
                '/products/indestructible-chew-toy/indestructible-chew-toy-5.jpg',
                '/products/indestructible-chew-toy/indestructible-chew-toy-6.jpg',
                '/products/indestructible-chew-toy/indestructible-chew-toy-7.jpg',
                '/products/indestructible-chew-toy/indestructible-chew-toy-8.jpg',
            ],
            'stock' => 15,
            'published' => false,
        ],
        [
            'id' => 'jnnj67b1h3',
            'name' => 'Calming Dog Bed',
            'slug' => 'calming-dog-bed',
            'category' => 'Grooming & Comfort',
            'price' => 43999,
            'price_usd' => 49.99,
            'shortDescription' => 'Soft, cozy bed for anxious puppies',
            'description' => 'Ultra-soft calming bed designed to provide comfort and security for anxious puppies. Features raised edges that create a safe, den-like environment perfect for separation anxiety. Machine washable cover and orthopedic support for growing pups.',
            'images' => [
                '/products/calming-dog-bed/calming-dog-bed-1.webp',
                '/products/calming-dog-bed/calming-dog-bed-2.webp',
                '/products/calming-dog-bed/calming-dog-bed-3.webp',
                '/products/calming-dog-bed/calming-dog-bed-4.webp',
                '/products/calming-dog-bed/calming-dog-bed-5.webp',
                '/products/calming-dog-bed/calming-dog-bed-6.webp',
                '/products/calming-dog-bed/calming-dog-bed-7.webp',
                '/products/calming-dog-bed/calming-dog-bed-8.webp',
            ],
            'stock' => 12,
            'published' => true,
        ],
        [
            'id' => 'km3jy4eqg0',
            'name' => 'No-Pull Harness',
            'slug' => 'no-pull-harness',
            'category' => 'Training & Safety',
            'price' => 9999,
            'price_usd' => 29.99,
            'shortDescription' => 'Safe, adjustable no-pull harness for growing pups',
            'description' => 'Perfect for first walks and training! This adjustable no-pull harness grows with your puppy, featuring multiple sizing points for a secure, comfortable fit. No-pull design protects your puppy\'s neck and provides better control during training walks.',
            'images' => [
                '/products/no-pull-harness/no-pull-harness-1.webp',
                '/products/no-pull-harness/no-pull-harness-2.webp',
                '/products/no-pull-harness/no-pull-harness-3.webp',
                '/products/no-pull-harness/no-pull-harness-4.webp',
                '/products/no-pull-harness/no-pull-harness-5.webp',
                '/products/no-pull-harness/no-pull-harness-6.webp',
                '/products/no-pull-harness/no-pull-harness-7.webp',
                '/products/no-pull-harness/no-pull-harness-8.webp',
            ],
            'stock' => 25,
            'published' => true,
        ],
        [
            'id' => 4,
            'name' => 'Dog Paw Washer Cup',
            'slug' => 'dog-paw-washer-cup',
            'category' => 'Grooming & Comfort',
            'price' => 10200,
            'price_usd' => 6.80,
            'shortDescription' => 'Easy-to-use paw cleaning system',
            'description' => 'Keep your home clean with this convenient paw washer cup! Simply fill with water, insert your puppy\'s paw, and the soft silicone bristles gently remove dirt and mud. Quick-dry design means no more muddy paw prints throughout your house.',
            'images' => [
                '/products/dog-paw-washer-cup/dog-paw-washer-cup-1.jpg',
                '/products/dog-paw-washer-cup/dog-paw-washer-cup-2.png',
                '/products/dog-paw-washer-cup/dog-paw-washer-cup-3.png',
                '/products/dog-paw-washer-cup/dog-paw-washer-cup-4.png',
                '/products/dog-paw-washer-cup/dog-paw-washer-cup-5.png',
            ],
            'stock' => 16,
            'published' => false,
        ],
        [
            'id' => 5,
            'name' => 'Grooming Glove',
            'slug' => 'grooming-glove',
            'category' => 'Grooming & Comfort',
            'price' => 1500,
            'price_usd' => 1,
            'shortDescription' => 'Gentle grooming glove for puppy coat care',
            'description' => 'Complete grooming glove designed for sensitive puppy skin. The soft, flexible design allows for comfortable grooming while removing loose hair and dirt. Perfect for maintaining a clean, healthy coat while bonding with your pup.',
            'images' => [
                '/products/grooming-glove/grooming-glove-3.jpg',
                '/products/grooming-glove/grooming-glove-1.avif',
                '/products/grooming-glove/grooming-glove-2.avif',
                '/products/grooming-glove/grooming-glove-4.jpg',
                '/products/grooming-glove/grooming-glove-5.png',
                '/products/grooming-glove/grooming-glove-6.png',
                '/products/grooming-glove/grooming-glove-7.png',
                '/products/grooming-glove/grooming-glove-8.png',
            ],
            'stock' => 14,
            'published' => true,
            'list_in_catalog' => false,
        ],
        [
            'id' => 6,
            'name' => 'Feeding Bowl',
            'slug' => 'feeding-bowl',
            'category' => 'Feeding',
            'price' => 8000,
            'price_usd' => 5.33,
            'shortDescription' => 'Durable feeding bowl for puppies',
            'description' => 'Designed for healthy feeding habits. The unique design encourages your puppy to eat at a comfortable pace. Made from food-safe, BPA-free materials that are easy to clean and dishwasher safe.',
            'images' => [
                '/products/feeding-bowl/feeding-bowl-1.jpg',
                '/products/feeding-bowl/feeding-bowl-2.png',
                '/products/feeding-bowl/feeding-bowl-3.png',
                '/products/feeding-bowl/feeding-bowl-4.png',
            ],
            'stock' => 20,
            'published' => false,
        ],
        [
            'id' => 7,
            'name' => 'Roll N Lick Ball',
            'slug' => 'roll-n-lick-ball',
            'category' => 'Play & Teething',
            'price' => 8500,
            'price_usd' => 5.67,
            'shortDescription' => 'Interactive treat-dispensing ball for mental stimulation',
            'description' => 'Keep your puppy engaged and entertained with this interactive roll and lick ball! Perfect for mental stimulation and slow feeding, this durable ball dispenses treats as your pup plays. The textured surface provides a satisfying licking experience while encouraging natural foraging behaviors. Made from food-safe materials, easy to clean, and perfect for keeping your puppy busy and happy.',
            'images' => [
                '/products/roll-n-lick-ball/roll-n-lick-ball-1.jpg',
                '/products/roll-n-lick-ball/roll-n-lick-ball-2.jpg',
                '/products/roll-n-lick-ball/roll-n-lick-ball-3.png',
                '/products/roll-n-lick-ball/roll-n-lick-ball-4.png',
                '/products/roll-n-lick-ball/roll-n-lick-ball-5.png',
                '/products/roll-n-lick-ball/roll-n-lick-ball-6.png',
            ],
            'stock' => 18,
            'published' => false,
        ],
];
