<?php
/**
 * Single source of product data. Require once per request; sets $products.
 * Used by products.php, product.php, cart.php, checkout.php, success.php.
 */
require_once __DIR__ . '/config.php';

$products = [
        [
            'id' => 1,
            'name' => 'Calming Dog Bed',
            'slug' => 'calming-dog-bed',
            'category' => 'Grooming & Comfort',
            'price' => 43999,
            'price_usd' => 49.99,
            'shortDescription' => 'Soft, cozy bed for anxious puppies',
            'description' => 'Ultra-soft calming bed designed to provide comfort and security for anxious puppies. Features raised edges that create a safe, den-like environment perfect for separation anxiety. Machine washable cover and orthopedic support for growing pups.',
            'images' => [
                '/products/calming-dog-bed/calming-dog-bed-1.webp',
                '/products/calming-dog-bed/calming-dog-bed-2.webp',
                '/products/calming-dog-bed/calming-dog-bed-3.webp',
                '/products/calming-dog-bed/calming-dog-bed-4.webp',
                '/products/calming-dog-bed/calming-dog-bed-5.webp',
                '/products/calming-dog-bed/calming-dog-bed-6.webp',
                '/products/calming-dog-bed/calming-dog-bed-7.webp',
                '/products/calming-dog-bed/calming-dog-bed-8.webp',
            ],
            'stock' => 12,
            'published' => true,
        ],
        [
            'id' => 2,
            'name' => 'No-Pull Harness',
            'slug' => 'no-pull-harness',
            'category' => 'Training & Safety',
            'price' => 9999,
            'price_usd' => 29.99,
            'shortDescription' => 'Safe, adjustable no-pull harness for growing pups',
            'description' => 'Perfect for first walks and training! This adjustable no-pull harness grows with your puppy, featuring multiple sizing points for a secure, comfortable fit. No-pull design protects your puppy\'s neck and provides better control during training walks.',
            'images' => [
                '/products/no-pull-harness/puppy-wearing-our-no-pull-harness.webp',
                '/products/no-pull-harness/no-pull-harness-1.webp',
                '/products/no-pull-harness/no-pull-harness-2.webp',
                '/products/no-pull-harness/no-pull-harness-3.webp',
                '/products/no-pull-harness/no-pull-harness-4.webp',
                '/products/no-pull-harness/no-pull-harness-5.webp',
                '/products/no-pull-harness/no-pull-harness-6.webp',
                '/products/no-pull-harness/no-pull-harness-7.webp',
                '/products/no-pull-harness/no-pull-harness-8.webp',
            ],
            'stock' => 25,
            'published' => true,
        ],
        [
            'id' => 3,
            'name' => 'Puppy Chew Toy with Treat Dispenser',
            'slug' => 'puppy-chew-toy-with-treat-dispenser',
            'category' => 'Play & Teething',
            'price' => 8500,
            'price_usd' => 5.67,
            'shortDescription' => 'Interactive chew toy that dispenses treats as your pup plays',
            'description' => 'Keep teething puppies entertained with this durable treat-dispensing chew toy. Fill it with kibble or small treats and let your pup roll, chew, and lick their way to a reward. Non-toxic materials help soothe sore gums while encouraging natural foraging behavior.',
            'images' => [
                '/products/Puppy Chew Toy with Treat Dispenser/S30197b04696c4bc8b7b929aa338f9600G.jpg_960x960q75.jpg_.avif',
                '/products/Puppy Chew Toy with Treat Dispenser/Sc6a1adcbcc9148c4b132a1a32b9c4ebeN.jpg_960x960q75.jpg_.avif',
                '/products/Puppy Chew Toy with Treat Dispenser/Sd8b4286ea4454746aeb9a24ca2ffb0a7Z.jpg_960x960q75.jpg_.avif',
            ],
            'stock' => 18,
            'published' => true,
        ],
        [
            'id' => 4,
            'name' => 'Puppy Collar',
            'slug' => 'puppy-collar',
            'category' => 'Training & Safety',
            'price' => 4500,
            'price_usd' => 3.00,
            'shortDescription' => 'Adjustable nylon collar sized for growing puppies',
            'description' => 'A lightweight, adjustable nylon collar designed for puppies. Durable buckle and D-ring for leash attachment. Comfortable fit that adjusts as your pup grows — perfect for early training and everyday walks.',
            'images' => [
                '/products/puppy colar/Medium_Nylon_Collar.webp',
            ],
            'stock' => 20,
            'published' => true,
        ],
        [
            'id' => 5,
            'name' => 'Puppy Dry Food',
            'slug' => 'puppy-dry-food',
            'category' => 'Feeding',
            'price' => 12000,
            'price_usd' => 8.00,
            'shortDescription' => 'Balanced dry food formulated for growing puppies',
            'description' => 'Nutrient-rich dry food specially formulated to support healthy growth in puppies. Packed with protein, vitamins, and minerals your pup needs for strong bones, a shiny coat, and steady energy throughout the day.',
            'images' => [
                '/products/puppy dry food/MG_6526.webp',
            ],
            'stock' => 15,
            'published' => true,
        ],
        [
            'id' => 6,
            'name' => 'Puppy Freeze-Dried Training Treats',
            'slug' => 'puppy-freeze-dried-training-treats',
            'category' => 'Feeding',
            'price' => 6500,
            'price_usd' => 4.33,
            'shortDescription' => 'High-value freeze-dried treats for puppy training',
            'description' => 'Small, soft freeze-dried training treats that puppies love. Perfect for positive reinforcement during obedience training, crate training, and socialization. Single-ingredient, easy to break into tiny pieces.',
            'images' => [
                '/products/puppy Freeze-Dried Training Treats/MG_7377.webp',
            ],
            'stock' => 20,
            'published' => true,
        ],
        [
            'id' => 7,
            'name' => 'Puppy Pad',
            'slug' => 'puppy-pad',
            'category' => 'Training & Safety',
            'price' => 5500,
            'price_usd' => 3.67,
            'shortDescription' => 'Absorbent potty training pads for puppies',
            'description' => 'Super-absorbent potty training pads with leak-proof backing. Ideal for housebreaking puppies, crate training, or travel. Quick-dry top layer keeps paws dry and helps protect your floors during the training phase.',
            'images' => [
                '/products/puppy pad/MG_5965.webp',
            ],
            'stock' => 25,
            'published' => true,
        ],
        [
            'id' => 8,
            'name' => 'Puppy Wash Shampoo',
            'slug' => 'puppy-wash-shampoo',
            'category' => 'Grooming & Comfort',
            'price' => 4800,
            'price_usd' => 3.20,
            'shortDescription' => 'Gentle shampoo formulated for sensitive puppy skin',
            'description' => 'Mild, tear-free shampoo designed for puppies with sensitive skin. Cleans without stripping natural oils, leaving your pup\'s coat soft and fresh. Free from harsh chemicals — safe for frequent baths during messy puppy adventures.',
            'images' => [
                '/products/puppy wash shampoo/MG_6412.webp',
            ],
            'stock' => 18,
            'published' => true,
        ],
        [
            'id' => 9,
            'name' => 'Puppy Enzymatic Cleaner',
            'slug' => 'puppy-enzymatic-cleaner',
            'category' => 'Grooming & Comfort',
            'price' => 5200,
            'price_usd' => 3.47,
            'shortDescription' => 'Enzyme cleaner for puppy accidents and odors',
            'description' => 'Powerful enzymatic formula breaks down urine, feces, and organic stains at the source. Eliminates odors rather than masking them — essential for potty training success. Safe to use on carpets, floors, and upholstery.',
            'images' => [
                '/products/puppy-enzymatic-cleaner/MG_6399.webp',
            ],
            'stock' => 16,
            'published' => true,
        ],
        [
            'id' => 10,
            'name' => 'Puppy Stainless Bowl',
            'slug' => 'puppy-stainless-bowl',
            'category' => 'Feeding',
            'price' => 7500,
            'price_usd' => 5.00,
            'shortDescription' => 'Durable stainless steel bowl for food and water',
            'description' => 'Rust-resistant stainless steel bowl sized for puppies. Non-slip base prevents spills during enthusiastic eating. Easy to clean, dishwasher safe, and built to last through teething, chewing, and daily mealtime chaos.',
            'images' => [
                '/products/puppy-stainless-bowl/Semi_Medium_Dog_Plate.webp',
                '/products/puppy-stainless-bowl/51Cp7G1+6CL._AC_SX679_.jpg',
                '/products/puppy-stainless-bowl/51Y1Kx0JwCL._AC_SX679_.jpg',
                '/products/puppy-stainless-bowl/615bSqdyZ+L._AC_SX679_.jpg',
                '/products/puppy-stainless-bowl/61SDpxPniJL._AC_SX679_.jpg',
                '/products/puppy-stainless-bowl/71MRo6RGPwL._AC_SX679_.jpg',
                '/products/puppy-stainless-bowl/71NLdQMlWjL._AC_SX679_.jpg',
            ],
            'stock' => 22,
            'published' => true,
        ],
        [
            'id' => 11,
            'name' => 'Puppy Treats',
            'slug' => 'puppy-treats',
            'category' => 'Feeding',
            'price' => 6000,
            'price_usd' => 4.00,
            'shortDescription' => 'Tasty lamb bite treats puppies love',
            'description' => 'Soft, flavorful lamb bite treats perfect for rewarding good behavior. Sized for small mouths and easy to chew. A great everyday snack or training reward for puppies of all breeds.',
            'images' => [
                '/products/puppy-treats/Sigma-Dog-Bite-Lamb.jpeg',
            ],
            'stock' => 20,
            'published' => true,
        ],
];
